Fixed build error
Removed the code that caused "undefined reference to `load_icon'" when building.
Instead of loading the icon in app it will use a '.desktop' file to launch wich includes the icon